from django.urls import path

from .views import (
    index,
    TopicListView,
    RedactorListView,
    RedactorDetailView,
    RedactorUpdateView,
    RedactorDeleteView,
    NewsPaperListView,
    NewsPaperDetailView,
    NewsPaperDeleteView,
    NewsPaperUpdateView,
    RedactorCreateView,
    TopicCreateView,
    NewsPaperCreateView, TopicUpdateView, TopicDeleteView, toggle_assign_to_article,
)


urlpatterns = [
    path("", index, name="index"),
    path("redactors/",
         RedactorListView.as_view(),
         name="redactor-list",
         ),
    path("redactors/<int:pk>/",
         RedactorDetailView.as_view(),
         name="redactor-detail",
         ),
    path("redactors/create/",
         RedactorCreateView.as_view(),
         name="redactor-create",
         ),
    path("redactors/<int:pk>/update/",
         RedactorUpdateView.as_view(),
         name="redactor-update",
         ),
    path("redactors/<int:pk>/delete/",
         RedactorDeleteView.as_view(),
         name="redactor-delete",
         ),
    path("topics/",
         TopicListView.as_view(),
         name="topic-list",
         ),
    path("topics/create/",
         TopicCreateView.as_view(),
         name="topic-create",
         ),
    path("topics/<int:pk>/update/",
         TopicUpdateView.as_view(),
         name="topic-update",
         ),
    path("topics/<int:pk>/delete/",
         TopicDeleteView.as_view(),
         name="topic-delete",
         ),
    path("newspapers/",
         NewsPaperListView.as_view(),
         name="newspaper-list",
         ),
    path("newspapers/create/",
         NewsPaperCreateView.as_view(),
         name="newspaper-create",
         ),
    path("newspapers/<int:pk>/",
         NewsPaperDetailView.as_view(),
         name="newspaper-detail",
         ),
    path("newspapers/<int:pk>/update/",
         NewsPaperUpdateView.as_view(),
         name="newspaper-update",
         ),
    path("newspapers/<int:pk>/delete/",
         NewsPaperDeleteView.as_view(),
         name="newspaper-delete",
         ),
    path(
        "newspapers/<int:pk>/toggle-assign/",
        toggle_assign_to_article,
        name="toggle-article-assign",
    ),

]

app_name = "agency"
