# Generated by Django 4.1.7 on 2023-03-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
